### PR TITLE
I am going to lose my mind

### PR DESCRIPTION
**Pull request by CalmBubbles**
What changed
+ span end tag in html/main.html had a missing begin tag so it's removed
+ tried to fix something

Bugs
• the 'click me' link in html/main.html and the 'main page' link in html/sitelist.html are not working for me

### CODE REVIEW

**Comment by CalmBubbles** [comment]
Can't rebase lmao

**Review by SpiritAxolotl — APPROVED** [review]
looks good but why are there conflicts :what:

**Review by SpiritAxolotl — COMMENTED** [review]
e

**Comment by CalmBubbles** [comment]
I've managed to fix several stuff like

**Comment by SpiritAxolotl** [comment]
ok fixed

**Pull request closed without merging**
